name: playful-programming-web

services:
  web:
    env_file: .env
    build:
      context: .
      args:
        SITE_URL: http://localhost:8080
        GIT_COMMIT_REF: main
        PUBLIC_CLOUDINARY_CLOUD_NAME: $PUBLIC_CLOUDINARY_CLOUD_NAME
      secrets:
        - GITHUB_TOKEN
        - HOOF_AUTH_TOKEN
    ports:
      - "8080:80"
    develop:
      watch:
        - path: .
          action: rebuild

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
  HOOF_AUTH_TOKEN:
    environment: HOOF_AUTH_TOKEN
