name: destroy-dev

on:
  pull_request:
    types:
      - closed

jobs:
  destroy:
    if: github.repository_owner === 'unicorn-utterances'
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      # see https://dev.to/bobheadxi/branch-previews-with-google-app-engine-and-github-actions-3pco
      - name: Extract branch name
        id: get_branch
        shell: bash
        env:
          PR_HEAD: ${{ github.head_ref }}
        run: echo "##[set-output name=branch;]$(echo ${PR_HEAD#refs/heads/} | tr / -)"

      - name: Remove files from DigitalOcean Spaces
        uses: vitorsgomes/s3-rm-action@v1.0.1
        with:
          args: --recursive
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: https://sfo2.digitaloceanspaces.com
          PATH_TO_DELETE: "${{ steps.get_branch.outputs.branch }}"

      - name: Mark environment as deactivated
        uses: bobheadxi/deployments@v0.4.3
        with:
          step: deactivate-env
          token: ${{ github.token }}
          env: ${{ steps.get_branch.outputs.branch }}
          desc: Deployment was pruned
          
