name: Fly PR Deploy

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  APP_NAME: pr-${{ github.event.pull_request.number }}-${{ github.repository_owner }}-${{ github.event.repository.name }}
  EVENT_ACTION: ${{ github.event.action }}
  FLY_API_TOKEN: ${{ secrets.FLY_WEB_PR_REVIEW_TOKEN }}
  DOCKER_TAG: ${{ github.repository_owner }}/${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}:${{ github.sha }}

jobs:
  review_app:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}-deploy

    environment:
      name: review
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: Set up Docker Buildx
        if: ${{ github.event.action != 'closed' }}
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        if: ${{ github.event.action != 'closed' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            "ENABLE_DISCOVERABILITY=false"
            "GIT_COMMIT_REF=${{ github.ref_name }}"
            "PUBLIC_CLOUDINARY_CLOUD_NAME=dssjarn7f"
            "SITE_URL=https://playfulprogramming.com"
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
            "HOOF_AUTH_TOKEN=${{ secrets.HOOF_AUTH_TOKEN }}"

      - id: status
        name: Retrieve app status
        run: flyctl status --app "$APP_NAME"
        continue-on-error: true

      - name: Destroy app
        if: ${{ github.event.action == 'closed' }}
        run: flyctl apps destroy "$APP_NAME" -y || true

      - name: Configure app
        if: ${{ github.event.action != 'closed' && steps.status.outcome == 'failure' }}
        run: |
          # Backup the original config file since 'flyctl launch' messes up the [build.args] section
          cp fly.toml fly.toml.bak

          flyctl launch --no-deploy --copy-config --name "$APP_NAME"

          # Restore the original config file
          cp fly.toml.bak fly.toml

      - id: deploy
        name: Deploy app
        if: ${{ github.event.action != 'closed' }}
        run: |
          flyctl deploy --config "fly.review.toml" --app "$APP_NAME" --image "$DOCKER_TAG" --ha=false

          # Make the deployment URL available to the GitHub workflow.
          flyctl status --app "$APP_NAME" --json >status.json
          hostname=$(jq -r .Hostname status.json)
          echo "url=https://$hostname" >> $GITHUB_OUTPUT
