name: Fly PR Deploy

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  APP_NAME: pr-${{ github.event.pull_request.number }}-${{ github.event.repository.name }}
  EVENT_ACTION: ${{ github.event.action }}
  FLY_API_TOKEN: ${{ secrets.FLY_WEB_DEPLOY_TOKEN }}

jobs:
  review_app:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}-deploy

    environment:
      name: review
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@1.5

      - id: status
        name: Retrieve app status
        run: flyctl status --app "$APP_NAME"
        continue-on-error: true

      - name: Destroy app
        if: ${{ github.event.action == 'closed' }}
        run: flyctl apps destroy "$APP_NAME" -y || true

      - name: Configure app
        if: ${{ github.event.action != 'closed' && steps.status.outcome == 'failure' }}
        run: |
          # Backup the original config file since 'flyctl launch' messes up the [build.args] section
          cp fly.toml fly.toml.bak

          flyctl launch --no-deploy --copy-config --name "$APP_NAME"

          # Restore the original config file
          cp fly.toml.bak fly.toml

      - name: Deploy app
        if: ${{ github.event.action != 'closed' }}
        run: fly deploy --config "fly.review.toml" --app "$APP_NAME" --remote-only --build-secret "GITHUB_TOKEN=$GITHUB_TOKEN" --build-secret "HOOF_AUTH_TOKEN=$HOOF_AUTH_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOOF_AUTH_TOKEN: ${{ secrets.HOOF_AUTH_TOKEN }}
